server:
  port:8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tryMeDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      spring:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true